#!/usr/bin/env node

const readline = require('readline');
const library  = require('./app/models.js');
const add      = require('./app/add.js');
const show     = require('./app/show.js');
const play     = require('./app/play.js');
const error    = require('./app/error.js');
const print    = require('./app/print.js');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Initial greeting
console.log('Welcome to your music collection!')
// Initialize the library
queryLibrary();

// Recursive function that asks for input, parses the first argument of the
// input, and sends the request to the correct handling function.
function queryLibrary() {
  rl.question('> ', (req) => {
    var args = req.trim().split(' ');
    switch(args[0]) {
      case 'add':
        print.response(add.album(req));
        break;

      case 'play':
        print.response(play.album(req));
        break;

      case 'show':
        switch(args[1]) {
          case 'unplayed':
            if (args.length > 2) {
              print.list(show.unplayedByArtist(req));
            } else {
              print.list(show.unplayed());
            }
            break;

          case 'all':
            if (args.length > 2) {
              print.list(show.allByArtist(req));
            } else {
              print.list(show.all());
            }
            break;

          default:
            print.response(error.unknownRequest());
        }
        break;

      case 'quit':
        print.response('Bye!');
        rl.close();
        return;

      default:
        print.response(error.unknownRequest());
    }
    // Unless the user typed 'quit', recurse through the function again.
    queryLibrary();
  });
};
